apiVersion: v1
kind: Secret
metadata:
  name: Secret-dockerhub
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: CgogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJuYWxpbmlzZWx2IiwKICAgICAgInBhc3N3b3JkIjogImRja3JfcGF0X1FVcG5KUVlpWDNGT21qZkl2OXJkQUFvMFRHbyIsCiAgICAgICJlbWFpbCI6ICJuYWxpbmkucy5tZWdAZ21haWwuY29tIiwKICAgICAgImF1dGgiOiAiYm1Gc2FXNXBjMlZzZGpwa1kydHlYM0JoZEY5UlZYQnVTbEZaYVZnelJrOXRhbVpKZGpseVpFRkJiekJVUjI4PSIKICAgIH0KICB9Cn0KCg==