apiVersion: v1
kind: Service
metadata:
  name: trend
  tier: 1
spec:
  type: Loadbalancer
  selector:
    app: trend
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP

      
      